### ISSUE TITLE
Using a private npm package in package.json an exception is thrown when bundling the project

### ISSUE THREAD

**Issue by ethikz** [liferay/liferay-npm-build-tools#109]
I'm trying to use this tool and in my `package.json` I have a privately hosted repo that is versioned and liferay-npm-bundler throws an error:

```
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open ':/github.com/package/package.git/package.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at readJsonSync (./node_modules/read-json-sync/index.js:10:31)
    at ./node_modules/liferay-npm-bundler/lib/index.js:147:49
    at Array.forEach (<anonymous>)
    at ./node_modules/liferay-npm-bundler/lib/index.js:141:31
    at Array.forEach (<anonymous>)
    at copyRootPackageJson (./node_modules/liferay-npm-bundler/lib/index.js:140:38)
    at Object.exports.default (./node_modules/liferay-npm-bundler/lib/index.js:25:16)
    at Object.<anonymous> (./node_modules/liferay-npm-bundler/bin/liferay-npm-bundler.js:2:32)
```

my `package.json` looks like this:

```
"devDependencies": {
    "private-package": "https://github.com/package/package.git",
  },
```

In order to show the correct path I have to add spaces to the beginning of the url but it still strips out the extra `/`:

```
Error: ENOENT: no such file or directory, open 'https:/github.com/package/package.git/package.json'
```

**Comment by izaera** [comment]
Hi @ethikz:

Please use version 1.6.2 of liferay-npm-bundler, where this should be fixed.
