### ISSUE TITLE
Running `npm run deploy` on new module causes build errors

### ISSUE THREAD

**Issue by ethib137** [liferay/liferay-npm-build-tools#221]
I just installed generator-liferay-bundle created a new react module and tried to deploy it. This failed to build and produced some errors. I'm wondering if there is some other global dependency it is expecting. 

Best,

```
➜  test-react-portlet npm run deploy

> test-react-portlet@1.0.0 deploy /Users/evanthibodeau/Documents/Dev/Demos/apps/modules/test-react-portlet
> npm run build && lnbs-deploy


> test-react-portlet@1.0.0 build /Users/evanthibodeau/Documents/Dev/Demos/apps/modules/test-react-portlet
> babel --source-maps -d build src && npm run copy-assets && liferay-npm-bundler

src/AppComponent.js -> build/AppComponent.js
src/index.js -> build/index.js

> test-react-portlet@1.0.0 copy-assets /Users/evanthibodeau/Documents/Dev/Demos/apps/modules/test-react-portlet
> lnbs-copy-assets

Project assets copied.
? May liferay-npm-bundler anonymously report usage statistics to improve the tool over time? Yes
Bundling 7 dependencies...
[BABEL] Note: The code generator has deoptimised the styling of "/Users/evanthibodeau/Documents/Dev/Demos/apps/modules/test-react-portlet/build/node_modules/react-dom@16.5.2/cjs/react-dom.development.js" as it exceeds the max of "500KB".
[BABEL] Note: The code generator has deoptimised the styling of "/Users/evanthibodeau/Documents/Dev/Demos/apps/modules/test-react-portlet/build/node_modules/react-dom@16.5.2/umd/react-dom.development.js" as it exceeds the max of "500KB".
Bundling took 12s
Report written to liferay-npm-bundler-report.html
/Users/evanthibodeau/Documents/Dev/Demos/apps/modules/test-react-portlet/node_modules/liferay-npm-build-support/lib/scripts/deploy.js:15
	_fs2.default.copyFileSync(_path2.default.join(outputDir, jarName), _path2.default.join(liferayDir, 'osgi', 'modules', jarName));
	             ^

TypeError: _fs2.default.copyFileSync is not a function
    at Object.exports.default (/Users/evanthibodeau/Documents/Dev/Demos/apps/modules/test-react-portlet/node_modules/liferay-npm-build-support/lib/scripts/deploy.js:15:15)
    at Object.<anonymous> (/Users/evanthibodeau/Documents/Dev/Demos/apps/modules/test-react-portlet/node_modules/liferay-npm-build-support/bin/lnbs-deploy.js:2:41)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-react-portlet@1.0.0 deploy: `npm run build && lnbs-deploy`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test-react-portlet@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by izaera** [comment]
I always try to keep up with the latest node version (f.e: I'm using 9.8.0 in my machine), but it's true that we don't have an specific requirement. I'll try to fix one with the QA team so that we can make a clear statement on what users need.

Thx.
