### ISSUE TITLE
Replace browser modules plugin fails with non-existent files

### ISSUE THREAD

**Issue by rozamirandar** [liferay/liferay-npm-build-tools#226]
@izaera 

When a create a simple portlet using the '@amcharts/amcharts4' library I get an error on `npm run build` when the plugin `liferay-npm-bundler-plugin-replace-browser-modules` runs. I'm attaching the stacktrace.

<pre>
> react-amcharts@1.0.0 build /home/rodolfo/Desenvolvimento/Liferay/react-amcharts
> babel --source-maps -d build src && npm run copy-assets && liferay-npm-bundler

src/AppComponent.js -> build/AppComponent.js
src/index.js -> build/index.js

> react-amcharts@1.0.0 copy-assets /home/rodolfo/Desenvolvimento/Liferay/react-amcharts
> lnbs-copy-assets

Project assets copied.
Bundling 167 dependencies...
Babel failed processing tiny-inflate@1.0.2/zlib.js: it will be copied verbatim (see report file for more info)
Babel failed processing cssom@0.3.4/lib/Parser.js: it will be copied verbatim (see report file for more info)
Babel failed processing object-inspect@1.4.1/test/lowbyte.js: it will be copied verbatim (see report file for more info)
Babel failed processing quote-stream@1.0.2/bin/cmd.js: it will be copied verbatim (see report file for more info)
Babel failed processing source-map@0.1.43/Makefile.dryice.js: it will be copied verbatim (see report file for more info)
{ Error: ENOENT: no such file or directory, open '/home/rodolfo/Desenvolvimento/Liferay/react-amcharts/build/node_modules/@amcharts%2Famcharts4@4.0.0-beta.79/jsdom/lib/jsdom/living/generated/utils.js'
    at Object.fs.openSync (fs.js:648:18)
    at Object.fs.writeFileSync (fs.js:1293:33)
    at ignoreFile (/home/rodolfo/Desenvolvimento/Liferay/react-amcharts/node_modules/liferay-npm-bundler-plugin-replace-browser-modules/lib/index.js:128:15)
    at /home/rodolfo/Desenvolvimento/Liferay/react-amcharts/node_modules/liferay-npm-bundler-plugin-replace-browser-modules/lib/index.js:80:4
    at Array.forEach (<anonymous>)
    at replaceModules (/home/rodolfo/Desenvolvimento/Liferay/react-amcharts/node_modules/liferay-npm-bundler-plugin-replace-browser-modules/lib/index.js:75:23)
    at Object.exports.default [as run] (/home/rodolfo/Desenvolvimento/Liferay/react-amcharts/node_modules/liferay-npm-bundler-plugin-replace-browser-modules/lib/index.js:18:4)
    at /home/rodolfo/Desenvolvimento/Liferay/react-amcharts/node_modules/liferay-npm-bundler/lib/runners.js:83:10
    at Array.forEach (<anonymous>)
    at runPlugins (/home/rodolfo/Desenvolvimento/Liferay/react-amcharts/node_modules/liferay-npm-bundler/lib/runners.js:69:10)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/rodolfo/Desenvolvimento/Liferay/react-amcharts/build/node_modules/@amcharts%2Famcharts4@4.0.0-beta.79/jsdom/lib/jsdom/living/generated/utils.js' }
</pre>

**Comment by izaera** [comment]
The failure can be reproduced with `amcharts4@4.0.0-beta.80`
